# Generated by Django 2.2.12 on 2020-04-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20200423_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category1',
            field=models.SmallIntegerField(choices=[(1, 'django'), (2, 'backend'), (3, 'python'), (4, 'programming'), (5, 'webdev')], default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='category2',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'django'), (2, 'backend'), (3, 'python'), (4, 'programming'), (5, 'webdev')], null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='category3',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'django'), (2, 'backend'), (3, 'python'), (4, 'programming'), (5, 'webdev')], null=True),
        ),
    ]
