# Generated by Django 2.2.12 on 2020-04-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_auto_20200424_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='counter',
            field=models.SmallIntegerField(default=0),
        ),
    ]
