# Generated by Django 2.2.12 on 2020-04-26 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_post_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approval',
        ),
    ]
